version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf