version: '3'
services:
  shard-0:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
  redis:
    image: redis:latest
  app:
    build: .
    ports:
      - "3001:3001"